version: '3'

services:
    api:
        build: .
        restart: always
        container_name: cinetic_api
        command: python manage.py runserver 127.0.0.1:8000
        volumes: 
            - .:/usr/app/cinetic_api
        ports:
            - 8000:8000

#volumes:
#    db-data: