# Generated by Django 4.1 on 2022-09-01 01:31

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('token', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cinema', models.CharField(max_length=20, unique=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_combo', models.CharField(max_length=20, unique=True)),
                ('nombre_combo', models.CharField(max_length=50)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pelicula', models.CharField(max_length=20, unique=True)),
                ('nombre_pelicula', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('clasificacion', models.CharField(max_length=20)),
                ('nombre_director', models.CharField(max_length=50)),
                ('fecha_filmacion', models.DateField(null=True)),
                ('sinopsis', models.CharField(max_length=255)),
                ('duracion', models.IntegerField()),
                ('caratula', models.FileField(upload_to='cinetic_app/caratula_peliculas/')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=20, unique=True)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ciudad', models.CharField(max_length=20)),
                ('inventario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(null=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VentaBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(null=True)),
                ('total', models.IntegerField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sala', models.CharField(max_length=20, unique=True)),
                ('nombre_sala', models.CharField(max_length=50)),
                ('tipo_sala', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField()),
                ('id_cinema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='ListaVentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_combo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.combo')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.producto')),
                ('id_venta_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.ventaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='IntegraCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField()),
                ('id_combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.combo')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_funcion', models.CharField(max_length=20, unique=True)),
                ('horario', models.TimeField(null=True)),
                ('fecha', models.DateField(null=True)),
                ('id_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.pelicula')),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_silla', models.CharField(max_length=3)),
                ('valor_boleta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_funcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.funcion')),
                ('id_vende_boletas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.ventaboleta')),
            ],
        ),
    ]
