# Generated by Django 4.1 on 2022-08-31 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cinema', models.CharField(max_length=20, unique=True)),
                ('ciudad', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_combo', models.CharField(max_length=20, unique=True)),
                ('nombre_combo', models.CharField(max_length=20)),
                ('descuento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('contrasenia', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pelicula', models.CharField(max_length=20, unique=True)),
                ('nombre_pelicula', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('clasificacion', models.CharField(max_length=20)),
                ('nombre_director', models.CharField(max_length=50)),
                ('fecha_filmacion', models.DateField(null=True)),
                ('sinopsis', models.CharField(max_length=100)),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=20, unique=True)),
                ('nombre_producto', models.CharField(max_length=20)),
                ('valor_compra', models.IntegerField()),
                ('valor_venta', models.IntegerField()),
                ('ciudad', models.CharField(max_length=20)),
                ('inventario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VendeProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vende_productos', models.CharField(max_length=20, unique=True)),
                ('fecha_venta', models.DateField(null=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='VendeBoletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vende_boletas', models.CharField(max_length=20, unique=True)),
                ('fecha_venta', models.DateField(null=True)),
                ('sillas_vendidas', models.IntegerField()),
                ('total', models.IntegerField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sala', models.CharField(max_length=20, unique=True)),
                ('nombre_sala', models.CharField(max_length=20)),
                ('tipo_sala', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField()),
                ('codigo_cinema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lista_compras', models.CharField(max_length=20, unique=True)),
                ('cantidad_productos', models.IntegerField()),
                ('cantidad_combos', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('codigo_combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.combo')),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.producto')),
                ('codigo_vende_productos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.vendeproductos')),
            ],
        ),
        migrations.CreateModel(
            name='IntegraCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_integra_combo', models.CharField(max_length=20, unique=True)),
                ('cantidad_producto', models.IntegerField()),
                ('codigo_combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.combo')),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_funcion', models.CharField(max_length=20, unique=True)),
                ('horario', models.CharField(max_length=20)),
                ('fecha', models.DateField(null=True)),
                ('codigo_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.pelicula')),
                ('codigo_sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_boleta', models.CharField(max_length=20, unique=True)),
                ('numero_silla', models.CharField(max_length=20)),
                ('valor_boleta', models.IntegerField()),
                ('codigo_funcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.funcion')),
                ('codigo_vende_boletas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.vendeboletas')),
            ],
        ),
    ]
