# Generated by Django 4.1 on 2022-09-03 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinetic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={},
        ),
        migrations.AlterModelManagers(
            name='empleado',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='password',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='username',
        ),
        migrations.AddField(
            model_name='cinema',
            name='nombre_cinema',
            field=models.CharField(default='No definido', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='caratula',
            field=models.ImageField(upload_to='cinetic_app/caratula_peliculas/'),
        ),
        migrations.AlterField(
            model_name='ventaboleta',
            name='fecha_venta',
            field=models.DateTimeField(auto_now_add=True, default='2022-09-03 18:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventaboleta',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.empleado'),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='fecha_venta',
            field=models.DateTimeField(auto_now_add=True, default='2022-09-03 18:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.empleado'),
        ),
    ]
