# Generated by Django 4.1 on 2022-09-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinetic_app', '0002_alter_empleado_options_alter_empleado_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='id_cinema',
            new_name='codigo_cinema',
        ),
    ]
