# Generated by Django 4.1 on 2022-09-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinetic_app', '0003_rename_id_cinema_sala_codigo_cinema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='codigo_cinema',
            new_name='cinema',
        ),
    ]
