# Generated by Django 4.1 on 2022-09-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinetic_app', '0005_rename_cinema_sala_cine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleta',
            old_name='id_funcion',
            new_name='funcion',
        ),
        migrations.RenameField(
            model_name='boleta',
            old_name='id_vende_boletas',
            new_name='vende_boletas',
        ),
        migrations.RenameField(
            model_name='funcion',
            old_name='id_pelicula',
            new_name='pelicula',
        ),
        migrations.RenameField(
            model_name='funcion',
            old_name='id_sala',
            new_name='sala',
        ),
        migrations.RenameField(
            model_name='integracombo',
            old_name='id_combo',
            new_name='combo',
        ),
        migrations.RenameField(
            model_name='integracombo',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='listaventaproducto',
            old_name='id_combo',
            new_name='combo',
        ),
        migrations.RenameField(
            model_name='listaventaproducto',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='listaventaproducto',
            old_name='id_venta_producto',
            new_name='venta_producto',
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='cine',
            new_name='cinema',
        ),
        migrations.RenameField(
            model_name='ventaboleta',
            old_name='id_empleado',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='ventaproducto',
            old_name='id_empleado',
            new_name='empleado',
        ),
    ]
