# Generated by Django 4.1 on 2022-09-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinetic_app', '0011_alter_empleado_options_alter_empleado_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='capacidad',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='caratula',
            field=models.ImageField(upload_to='peliculas/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('ACC', 'Accion'), ('AVR', 'Aventuras'), ('CFN', 'Ciencia ficcion'), ('COM', 'Comedia'), ('RMT', 'Romantica'), ('DRM', 'Drama'), ('TRR', 'Terror'), ('SPS', 'Suspenso')], default='ACC', max_length=3),
        ),
    ]
